### ISSUE TITLE
Missing repository updates for Firmware 4.1.12

### ISSUE THREAD

**Issue by cmosetick** [invizbox/firmware#1]
Hello, I am creating an issue here, because it seems that this repository has not been updated recently.

Their seems to be a new Firmware release for invizbox2 devices that has been published and released elsewhere as noted here in September 2021:
https://support.invizbox.com/hc/en-us/articles/4406218086289-InvizBox-2-Firmware-4-1-12-latest-

There is a number of items listed in the above mentioned Invizbox2 support page Changelog. It seems to me that many of the changes / fixes come from upstream OpenWRT, but it still would be good to know what, if, anything has changed in the build process for this new firmware.

I mostly am interested in the releases download page here being updated to reflect this new firmware release.

![Screenshot from 2021-09-23 13-32-50](https://user-images.githubusercontent.com/4873085/134493647-07159bfe-082f-491d-9d13-18f7e41528aa.png)

Thanks in advance for any clarifications or support you can provide.

**Comment by invizbox** [comment]
Hi @cmosetick, thanks for opening this. Releasing the code to GitHub is part of the release process. I was on holidays for the last two weeks and haven't got to it yet. I'll get to it over the next few days and will be happy to answer any question following the published changes.
Vincent

**Comment by gitnewcomer** [comment]
Hi @invizbox, where can I find the source code for firmware 4.1.12? I'm just seeing the source code for 0.1.7? Is there a new repository or something? Thanks!

**Comment by gitnewcomer** [comment]
@invizbox @VincentRiou is there any plan to update the source code on github or will it be now closed source?

**Comment by invizbox** [comment]
@gitnewcomer, it's most likely going to be a new repo for the code as we consolidated the 3 existing firmware repos into one. We're not planning to become closed source. We're sorry that we haven't put the code up for 4.1.12 yet. It's just a delay due to prioritising other tasks for @VincentRiou. We're going to bump that publication of the 4.1.12 source up. Thanks for your understanding.

**Comment by invizbox** [comment]
A number of changes:
* The [invizbox-2](https://github.com/invizbox/invizbox-2), [invizbox-go](https://github.com/invizbox/invizbox-go) and [invizbox-original](https://github.com/invizbox/invizbox-original) have been merged into this new repository. All remaining issues were migrated first. These initial repositories have been archived
* The [openwrt](https://github.com/invizbox/openwrt), [packages](https://github.com/invizbox/packages) and [luci](https://github.com/invizbox/luci) have been updated and tagged with 4.1.12
* The [invizbox-feed](https://github.com/invizbox/invizbox-feed) repository was moved to just [feed](https://github.com/invizbox/feed) for simplicity/clarity (old references are still valid and redirected) and tagged with 4.1.12
* The 4.1.12 code was pushed to this new repository and [released](https://github.com/invizbox/firmware/releases/tag/4.1.12)
* All other repositories have been archived (not used anymore)
