### ISSUE TITLE
Recursive dependency error while compiling firmware

### ISSUE THREAD

**Issue by gitnewcomer** [invizbox/firmware#5]
Hi, i'm trying to compile the new firmware for invizbox 2 but I'm always getting an recursive dependency error:

```
tmp/.config-package.in:117583:error: recursive dependency detected!
tmp/.config-package.in:117583:	symbol PACKAGE_tor depends on PACKAGE_tor-basic
tmp/.config-package.in:117609:	symbol PACKAGE_tor-basic is selected by PACKAGE_tor
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"
```
How can it be fixed? Thanks!

**Comment by VincentRiou** [comment]
Hi @gitnewcomer,
I also get these "expected" warning message when building the firmware but they don't result in an issue.
This is coming from the way the Tor package is currently structured in OpenWRT. 

The rest compiles well and the tor-basic package referenced is built and present on the firmware:

```
...
WARNING: Makefile 'package/feeds/packages/prometheus-node-exporter-lua/Makefile' has a dependency on 'bmx7-json', which does not exist
tmp/.config-package.in:117583:error: recursive dependency detected!
tmp/.config-package.in:117583:  symbol PACKAGE_tor depends on PACKAGE_tor-basic
tmp/.config-package.in:117609:  symbol PACKAGE_tor-basic is selected by PACKAGE_tor
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

#
# configuration written to .config
#
WARNING: Makefile 'package/feeds/packages/bmx7-dnsupdate/Makefile' has a dependency on 'bmx7', which does not exist
...
 make[3] -C feeds/packages/utils/rng-tools compile
 make[3] -C feeds/packages/net/tor compile
 make[3] -C package/network/utils/iw compile
...
Firmware built!
```

If you are failing to build, I have a feeling that is not the issue and I would need more info to reproduce/investigate.

If this is more of a rhetorical question about linux kernel recursive dependencies, you can find more in the kconfig language reference: https://www.kernel.org/doc/Documentation/kbuild/kconfig-language.txt

**Comment by gitnewcomer** [comment]
Hi @VincentRiou thanks for your reply.

I'm getting this additional error when I try to compile the firmware:

```
tmp/.config-package.in:1[175](https://github.com/gitnewcomer/invizbox-firmware/runs/5428641777?check_suite_focus=true#step:13:175)83:error: recursive dependency detected!
tmp/.config-package.in:117583:	symbol PACKAGE_tor depends on PACKAGE_tor-basic
tmp/.config-package.in:1[176](https://github.com/gitnewcomer/invizbox-firmware/runs/5428641777?check_suite_focus=true#step:13:176)09:	symbol PACKAGE_tor-basic is selected by PACKAGE_tor
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

Error opening terminal: unknown.
make[2]: *** [/workdir/openwrt/include/toplevel.mk:134: menuconfig] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [/workdir/openwrt/include/toplevel.mk:92: .config] Error 2
make: *** [/workdir/openwrt/include/toplevel.mk:228: world] Error 2
```

I'm using the same compiling environment that I used for the older firmware (where it compiled without a problem)...
I will check again if there is any problems with my compiling environment. :)

**Comment by VincentRiou** [comment]
Not sure what linux flavour you're using to build this but this error sounds like your TERM variable is not set.
This error seems to occur within the OpenWRT build. You could try a vanilla build of OpenWRT in your environment as you need that to work before you can build this firmware.
FYI, this firmware is based on OpenWRT 21.02 whereas the previous ones were on 18.06 - so you may want to look at the differences in build requirements between the two versions.

**Comment by gitnewcomer** [comment]
Hi @VincentRiou,
This was my problem:

> Not sure what linux flavour you're using to build this but this error sounds like your TERM variable is not set.

I'm using a Ubuntu Docker for compiling the firmware and I forgot to export the TERM variable before building the firmware:
```
export TERM=linux
```
Thanks for your help! :)
