### ISSUE TITLE
VPN change workaround ?

### ISSUE THREAD

**Issue by ghost** [invizbox/firmware#8]
Hacking a little the InvizBox 2 I had with ProtonVPN, I found that there's a easy way to just change the provider using the regular RESET function of the InvizBox.

RESETs are system-wide except for a partition /private , which contains the provider, the vpn-credentials and the router/wifi credentials.

- Changing with vim the provider ( Example: NordVPN ) and setting the vpn-credentials to blank.
- Resetting the Router using the reset.txt USB method.

Now I have NordVPN and all VPN settings for it on the InvizBox2.

Can we have a workaround on the GUI to just select a new provider, the UCI or a command will empty the vpn-credentials and change the provider to the selected one and from there the device will just ask to perform the reset.txt method ?

This will save some time for the folks who are working on this feature and want to have another provider.

**Comment by gitnewcomer** [comment]
I've already used this method to change my Invizbox to Windscribe VPN. Unfortunately I think this project is dead, because nobody is replying to the issues and the firmware doesn't have an update for long time. This could be a great product, but lacks some features, like letting us choose detailed WiFi settings or use Wireguard... Hope I'm wrong, but I would not count with a reply or change on this...

**Comment by ghost** [comment]
Oh, I see.

Pretty much all repos have not being updated, that's true. My box is at 4.3.4 and no public release or any new news from the team. 

Too bad, OpenWRT products are super easy to manage.

Thanks, I post it since was searching online and nobody was sharing this insight.

Than will not expect any reply from the devs than.

Other features will be very good, I like the way PiHole lets you see the DNS logs so you can trigger blocks for specific domains, was trying to get docker as well installed on it to test it but have no luck so far since the openwrt repos they use are pretty much on .onion sites. Switching to public ones might break it, even if the cpu arch is known.

At this point will be better to just compile OpenWRT than and install it on the hardware itself and setup the VPN manually there. What a shame, the UI at least is cleaner and very nooby ready.

**Comment by gitnewcomer** [comment]
The developer that always replied here has left Invizbox on April 2023 (https://www.linkedin.com/in/vincent-riou/), so this is why I tell that the project is dead. I think you can install luci on top and change the repos to the official openwrt (same major version). If you check the files from the update procedure, you will find that there is a fallback to normal repos instead tor (onion) ones...

**Comment by VincentRiou** [comment]
I may have left but the project is not dead. Historically, the stance on getting this feature is tracked here: https://support.invizbox.com/hc/en-us/articles/360007644997-Can-I-switch-VPN-providers-on-my-InvizBox-2- . The likelihood for this to be prioritised is low as you can see. That said, you now have a workaround.

**Comment by gitnewcomer** [comment]
Hi @VincentRiou, thanks for the reply.
Maybe the project is not dead, but it seems like it: there was no update for more than a year now. With you in the team, we fell that things were evolving :)
Wish you all the best for the future...

**Comment by ghost** [comment]
Hi @VincentRiou 

Thanks for the answer.

I know the project is not dead, since many providers, including VPNCity, current job if I'm not mistaken. Is also a provider for it so the community is very wide among a lot of developers and end-users interested on this technology.

But imagine that the article you can share us is from 2020 -> 4 years ago man.

Either the management for the project is focusing on another direction and they have not being too focus on the public aspect of the project or this is being develop by just a few that are left of what was the Invizbox team.

It's a good tech, many rivals are appearing and open-source communities move fast. 

Maybe getting some of the routers on flashrouters.com and starting with a White-Label distributor to bring Invizbox 3 with Wifi 6 and release on one go all this missing features will be at least a move for this startup to stay relevant on the field.

Many of us bought an idea, but this lack of public facing feels more like waiting for one day to have a router that can become a honeypot out of nowhere.
